name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: NuGet Restore Packages
      run: nuget restore Src/DSInternals.sln
